### ISSUE TITLE
What about Idris-Erlang

### ISSUE THREAD

**Issue by lenary** [llaisdy/beam_languages#5]
https://github.com/lenary/idris-erlang

Work I did a while ago, people are still interested, but nothing is mature enough yet, and my codebase was research-only.

**Comment by llaisdy** [comment]
Dear Sam

Thanks for your comment.  I'll add it and close this issue once I have.

I think the reason I didn't include it initially was that its focus seemed more  "erlang backend for Idris" rather than "BEAM language" - for example idris-erlang generates erlang source code.

However, you're right it will be of interest.

Best wishes

Ivan

**Comment by llaisdy** [comment]
Done.

**Comment by lenary** [comment]
Thanks. I don't mind it being put in a different category because it's research-grade, etc, but yes, the reason it compiles to erlang is not to compile to erlang, it's for the features of BEAM. The erlang it generates is basically unreadable.
